### ISSUE TITLE
[PBI-TOOLS 1.2] - Compilation Failed

### ISSUE THREAD

**Issue by djik92** [pbi-tools/pbi-tools#388]
Hello,

I want to compile a directory containing the extraction of a PBIT.

```sh
pbi-tools compile "c:\Users\xxx\Documents\PROJETS\AZURE\PBI\ASS-ASSIDUITE\pbi-tools\vbcode\ASS_SWS" ".\abc" -format PBIT
```

Here is the result:

```
Reading PBIXPROJ settings from: c:\Users\xxx\Documents\PROJETS\AZURE\PBI\ASS-ASSIDUITE\pbi-tools\vbcode\ASS_SWS\.pbixproj.json  
Using Power BI Desktop install: 2.140.1078.0 (25.02)+2cce24fb16e8b71ba835921d23e7ffc1fab909df at C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.140.1078.0_x64__8wekyb3d8bbwe\bin  
Generating PBIT file at 'C:\Users\xxx\Documents\PROJETS\AZURE\PBI\ASS-ASSIDUITE\pbi-tools\UC1_pbix_content\abc\ASS_SWS.pbit'...  
An unhandled exception occurred.  
System.MissingMethodException: Method not found: 'Void Microsoft.PowerBI.Packaging.PowerBIPackager.Save(Microsoft.PowerBI.Packaging.IPowerBIPackage, System.IO.Stream, Boolean)'.  
   at PbiTools.PowerBI.PbiPackage.Save(String path)  
   at PbiTools.Cli.CmdLineActions.CompilePbix(String folder, String outPath, PbiFileFormat format, Boolean overwrite) in X:\pbi-tools\BRANCHES\1.2\src\PBI-Tools\Cli\Compile.cs:line 90  
--- End of stack trace from the previous location where the exception was thrown ---  
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  
   at PowerArgs.ArgAction.Invoke()  
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\1.2\src\PBI-Tools\Program.cs:line 139  

```

Do you know what I need to do to make this code work?
Thank you for your help.

Version Information:

    PBI-TOOLS: 1.2
    PBI Desktop: 2.140.1078.0 64-bit (February 2025)
    Microsoft Windows 11 Education - 10.0.22631 Build 22631

**Comment by mertbakir** [comment]
I get the same error. I was on v1.0, and started getting this error, then upgraded to 1.2 and still the same. I guess PBI February update broke something.

**Comment by mthierba** [comment]
Can look at the end of the week (currently traveling). Recommend to stick to an earlier version of Desktop for now. (Which can be extracted into a custom folder so that your installed version isn't replaced: https://www.youtube.com/live/Xy3FFB3Jfdg)

**Comment by mthierba** [comment]
Furthermore, for the 'compile' command I'd recommend the pbi-tools.core version which doesn't have this dependency on PBI Desktop. This one is designed for CI/CD scenarios, where Desktop is not available. The 'pbi-tools.exe' version should be used for local development and the 'extract' command primarily.

**Comment by djik92** [comment]
I tested with the Core version, and the 'compile' works. Thanks for your help! :)

**Comment by mthierba** [comment]
For reference/comparison: https://pbi.tools/cli/feature-matrix.html (Core version prerequisite is now .Net 8/9 - docs need to be updated to reflect that)

**Comment by mthierba** [comment]
Keeping this open until the underlying issue in `pbi-tools.exe` has been fixed.

**Comment by radian21** [comment]
Chiming in that I'm experiencing the same behavior, but using the Core version is a successful workaround for the `compile` operation. Watching. Thanks.

**Comment by nickozz714** [comment]
Using the Core version, however I still get the following error when compiling:

Reading PBIXPROJ settings from: C:\Users\<user>\PycharmProjects\Power Bi Report Generator\AutoDashboard\.pbixproj.json
Using Power BI Desktop install: 2.142.928.0 (25.04)+de52df9f0bb74ad93a80d89c52d63fe6d07e0e1b at C:\Program Files\Microsoft Power BI Desktop\bin
Generating PBIT file at 'C:\Users\<user>\PycharmProjects\Power Bi Report Generator\AutoDashboard.pbit'...
An unhandled exception occurred.
System.MissingMethodException: Method not found: 'Void Microsoft.PowerBI.Packaging.PowerBIPackager.Save(Microsoft.PowerBI.Packaging.IPowerBIPackage, System.IO.Stream, Boolean)'.
   at PbiTools.PowerBI.PbiPackage.Save(String path)
   at PbiTools.Cli.CmdLineActions.CompilePbix(String folder, String outPath, PbiFileFormat format, Boolean overwrite) in X:\pbi-tools\BRANCHES\1.2\src\PBI-Tools\Cli\Compile.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\1.2\src\PBI-Tools\Program.cs:line 139

From the comments above I understood that 1.2.0. Core is not using Pbi Desktop. But it seems it does?

**Comment by nickozz714** [comment]
Experiencing the same issue, switching to core has worked for me. Using the Core now only for compiling a PBIT file.

**Comment by ErjunQ** [comment]
Same issue here

**Comment by TarekSalha** [comment]
yup, same issue, will use the core version for now

**Comment by Cecilia-BW** [comment]
@mthierba Hi Mathias, the desktop version used to work for me, but now I have the same compile issue. When I switched to Core, I got the message below to revert my .NET to version 8. I thought 9 is also supported. Is it something else that's wrong? Appreciate your guidance.

You must install or update .NET to run this application.

App: .\pbi-tools\pbi-tools.core.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: .\dotnet

The following frameworks were found:
  9.0.4 at [.\dotnet\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=win-x64&os=win10

**Comment by mthierba** [comment]
> @mthierba Hi Mathias, the desktop version used to work for me, but now I have the same compile issue. When I switched to Core, I got the message below to revert my .NET to version 8. I thought 9 is also supported. Is it something else that's wrong? Appreciate your guidance.
> 
> You must install or update .NET to run this application.
> 
> App: .\pbi-tools\pbi-tools.core.exe
> Architecture: x64
> Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
> .NET location: .\dotnet
> 
> The following frameworks were found:
>   9.0.4 at [.\dotnet\shared\Microsoft.NETCore.App]
> 
> Learn more:
> https://aka.ms/dotnet/app-launch-failed
> 
> To install missing framework, download:
> https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=win-x64&os=win10

If you don't have the .net8 runtime installed, use the "pbi-tools.net9.xxxxx" zip from the release - it is `pbi-tool.core`, but targeting .net9.

**Comment by Cecilia-BW** [comment]
> > [@mthierba](https://github.com/mthierba) Hi Mathias, the desktop version used to work for me, but now I have the same compile issue. When I switched to Core, I got the message below to revert my .NET to version 8. I thought 9 is also supported. Is it something else that's wrong? Appreciate your guidance.
> > You must install or update .NET to run this application.
> > App: .\pbi-tools\pbi-tools.core.exe
> > Architecture: x64
> > Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
> > .NET location: .\dotnet
> > The following frameworks were found:
> > 9.0.4 at [.\dotnet\shared\Microsoft.NETCore.App]
> > Learn more:
> > https://aka.ms/dotnet/app-launch-failed
> > To install missing framework, download:
> > https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=win-x64&os=win10
> 
> If you don't have the .net8 runtime installed, use the "pbi-tools.net9.xxxxx" zip from the release - it is `pbi-tool.core`, but targeting .net9.

It's working! Thank you so much for your quick response. All the best to you!

**Comment by VladimirUlz** [comment]
@mthierba , hi Mathias, use pbi-tool.core for compile PbixProj to format PBIT, thank you for this suggestion!

script works good but crashes wile compiling some files 
py`
PBI_TOOLS = "pbi-tools.core.exe" #1.2.0
PBI_TOOLS = "pbi-tools.exe" #
report_body = get_rs_response(f'{SERVICE_URL_TEST}/PowerBIReports({report_id})/Content/$value')
with open(f'report.pbix', 'wb') as f:
    f.write(report_body.content)
        
run_cmd(f'{PBI_TOOLS_2} extract ".\\report.pbix"')
run_cmd(f'{PBI_TOOLS} compile ".\\report" -format PBIT -outPath "report.pbit"')
        
# 
if not os.path.exists(".\\report.pbit"):
    raise FileNotFoundError("file report.pbit was not found")
        
with zipfile.ZipFile(f".\\report.pbit", 'r') as z:
    z.extractall(f".\pbit")
        
with open(f'.\pbit\DataModelSchema', encoding='utf_16_le') as f:
    d = json.load(f)
`

pbit file exist after running script but DataModelSchema doesn't exist

<img width="260" height="183" alt="Image" src="https://github.com/user-attachments/assets/ff992d07-0741-4afd-94af-89ffaa4ee97c" />


I want to get this folder

<img width="343" height="186" alt="Image" src="https://github.com/user-attachments/assets/9f3c266d-7b0c-4d2e-835f-fdf912ba86fb" />



Please tell me what the error might be related to?

**Comment by mthierba** [comment]
@VladimirUlz Your screenshot suggests that the project you're compiling is a "thin" report, i.e. one with a connection to a remote data model (hence the `Connections` part) instead of one that has the model included. That reflects what's in your source PBIX file. If you're expecting a PBIT output with `DataModelSchema`, please use a full/"thick" PBIX source file.

You mention an error, but you're not providing any error details. And the fact that you have a screenshot of the output makes me think there was no error in terms of producing a PBIT file?


> @mthierba , hi Mathias, use pbi-tool.core for compile PbixProj to format PBIT, thank you for this suggestion!
> 
> script works good but crashes wile compiling some files 
> py`
> PBI_TOOLS = "pbi-tools.core.exe" #1.2.0
> PBI_TOOLS = "pbi-tools.exe" #
> report_body = get_rs_response(f'{SERVICE_URL_TEST}/PowerBIReports({report_id})/Content/$value')
> with open(f'report.pbix', 'wb') as f:
>     f.write(report_body.content)
>         
> run_cmd(f'{PBI_TOOLS_2} extract ".\\report.pbix"')
> run_cmd(f'{PBI_TOOLS} compile ".\\report" -format PBIT -outPath "report.pbit"')
>         
> # 
> if not os.path.exists(".\\report.pbit"):
>     raise FileNotFoundError("file report.pbit was not found")
>         
> with zipfile.ZipFile(f".\\report.pbit", 'r') as z:
>     z.extractall(f".\pbit")
>         
> with open(f'.\pbit\DataModelSchema', encoding='utf_16_le') as f:
>     d = json.load(f)
> `
> 
> pbit file exist after running script but DataModelSchema doesn't exist
> 
> <img width="260" height="183" alt="Image" src="https://github.com/user-attachments/assets/ff992d07-0741-4afd-94af-89ffaa4ee97c" />
> 
> 
> I want to get this folder
> 
> <img width="343" height="186" alt="Image" src="https://github.com/user-attachments/assets/9f3c266d-7b0c-4d2e-835f-fdf912ba86fb" />
> 
> 
> 
> Please tell me what the error might be related to?

**Comment by VladimirUlz** [comment]
> [@VladimirUlz](https://github.com/VladimirUlz) Your screenshot suggests that the project you're compiling is a "thin" report, i.e. one with a connection to a remote data model (hence the `Connections` part) instead of one that has the model included. That reflects what's in your source PBIX file. If you're expecting a PBIT output with `DataModelSchema`, please use a full/"thick" PBIX source file.
> 
> You mention an error, but you're not providing any error details. And the fact that you have a screenshot of the output makes me think there was no error in terms of producing a PBIT file?
> 
> > [@mthierba](https://github.com/mthierba) , hi Mathias, use pbi-tool.core for compile PbixProj to format PBIT, thank you for this suggestion!
> > script works good but crashes wile compiling some files
> > py`
> > PBI_TOOLS = "pbi-tools.core.exe" [#1](https://github.com/pbi-tools/pbi-tools/issues/1).2.0
> > PBI_TOOLS = "pbi-tools.exe" #
> > report_body = get_rs_response(f'{SERVICE_URL_TEST}/PowerBIReports({report_id})/Content/$value')
> > with open(f'report.pbix', 'wb') as f:
> > f.write(report_body.content)
> > run_cmd(f'{PBI_TOOLS_2} extract ".\report.pbix"')
> > run_cmd(f'{PBI_TOOLS} compile ".\report" -format PBIT -outPath "report.pbit"')
> > 
> > if not os.path.exists(".\report.pbit"):
> > raise FileNotFoundError("file report.pbit was not found")
> > with zipfile.ZipFile(f".\report.pbit", 'r') as z:
> > z.extractall(f".\pbit")
> > with open(f'.\pbit\DataModelSchema', encoding='utf_16_le') as f:
> > d = json.load(f)
> > `
> > pbit file exist after running script but DataModelSchema doesn't exist
> > <img alt="Image" width="260" height="183" src="https://private-user-images.githubusercontent.com/146207379/484742482-ff992d07-0741-4afd-94af-89ffaa4ee97c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY4ODMwMjYsIm5iZiI6MTc1Njg4MjcyNiwicGF0aCI6Ii8xNDYyMDczNzkvNDg0NzQyNDgyLWZmOTkyZDA3LTA3NDEtNGFmZC05NGFmLTg5ZmZhYTRlZTk3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkwM1QwNjU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWJjMzhmODExNGExMmY0OGFkNTVlYzE5N2I2NzczMTZmY2IxNTllNDNlYTc1ZWVlNWFmMDljMTVlZjk0M2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZUbZlNeNwpChif6atKN6WCue6rlJXqFoz-b6ZrSwhrs">
> > I want to get this folder
> > <img alt="Image" width="343" height="186" src="https://private-user-images.githubusercontent.com/146207379/484745368-9f3c266d-7b0c-4d2e-835f-fdf912ba86fb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY4ODMwMjYsIm5iZiI6MTc1Njg4MjcyNiwicGF0aCI6Ii8xNDYyMDczNzkvNDg0NzQ1MzY4LTlmM2MyNjZkLTdiMGMtNGQyZS04MzVmLWZkZjkxMmJhODZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkwM1QwNjU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjhjNTg5MTZiMjM4ZDZiMDM2YzM5NDhhMjkzYjcxNTI2ZjlmNDRlNTc5NGFiZmJiMzk4MzUxYzBkOWUwNzdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mo1EpPcXGKJF9gLb5pabFrL1OjyOGcZcXV4xYEp3W-s">
> > Please tell me what the error might be related to?

@mthierba , If is "thin" report (remote connections to data model SSAS) then the file "DataModelSchema" will not be created, but only "Connections" file?

**Comment by mthierba** [comment]
@VladimirUlz Correct. "Thin" reports only have connection information about the remote model, but do not contain any further model metadata - that is resolved at runtime by the Power BI engine (including access permissions).

**Comment by pfeigl** [comment]
@mthierba Did you have a chance to look into the root issue? 

We are having a automated process where we extract, modify and compile PowerBI Templates on the fly. We could (as proposed here) also distribute the core version, but as we have to extract anyways, we would have to distribute two artifacts instead of one.

**Comment by mthierba** [comment]
> @mthierba Did you have a chance to look into the root issue? 
> 
> We are having a automated process where we extract, modify and compile PowerBI Templates on the fly. We could (as proposed here) also distribute the core version, but as we have to extract anyways, we would have to distribute two artifacts instead of one.
> 

@pfeigl The fix would be quite trivial. However, the tool requires a major refactoring of the release pipeline as I've switched from an owned signing certificate to a sponsored one. That is anything but trivial and not achievable this side of the new year due to demanding work and personal commitments.
All things considered, using both distributions in parallel seems very reasonable - the executables are tiny in size and allow xcopy deployments.
